### ISSUE TITLE
Demonstrate content negotation?

### ISSUE THREAD

**Issue by jberger** [ynonp/mojo-demos#1]
Hello Ynon,

I enjoyed your article on Mojo! Thanks for writing it. I couldn't figure out how to contact you so I opened this, if there is a better way, please let me know (and you are of course welcome to join us on irc.perl.org #mojo).

Anyway, though I think this is a very interesting example (I didn't know there was a module to generate an SVG calendar! isn't cpan amazing!) I wonder if you might take it a step further?

Mojo supplies a functionality to respond to the same route differently depending on what type of response you request. This can be in the form of a header, a query parameter, or especially interesting in this case, a file extension. You might show that the routes you make work, but that you can simplify that into detecting that the user wants an svg and responding in kind. The relevant documentation is [here](http://mojolicious.org/perldoc/Mojolicious/Guides/Rendering#Content-negotiation) and I have a plugin that uses it extensively [Mojolicious::Plugin::ReplyTable](https://metacpan.org/pod/Mojolicious::Plugin::ReplyTable) if you'd like to see it in action.

Once again, this isn't meant as a criticism, just a note. Please keep up the blogging, we're very happy to have you!

**Comment by ynonp** [comment]
Hi Joel,
Thanks - glad to hear you read and liked the post! Also my email is ynon at ynonperek.com (for next times)

I think content negotiation will just make things confusing in the SVG example. An image url should always return that image IMHO, so it'll be easy to share.

A better example I think for content negotiation is single page web applications that provide server side rendering. Then the same route should normally return an HTML page, but if JSON is requested it just sends the data. Sounds like a good idea to write a tutorial about as a future post :)

Glad to hear from you and keep on following,
  Ynon

**Comment by jberger** [comment]
> I think content negotiation will just make things confusing in the SVG example. An image url should always return that image IMHO, so it'll be easy to share.

You already are effectively doing content negotiation by choosing the form or the svg by file extension. All I was suggesting was to formalize that. That said I see your point.
